### ISSUE TITLE
Better refresh

### ISSUE THREAD

**Issue by maxemann96** [maxemann96/ghostpp#2]
Better rehost the game everytime, than refresh the game?

**Comment by keksd0se** [comment]
uint32_t refreshdelay = ( m_GHost->m_RefreshDuration < 180 ) ? m_GHost->m_RefreshDuration : ( GetTime( ) - m_CreationTime );

game_base.cpp

**Comment by stuartacott** [comment]
has anyone got a bot with !vote and !commands please

**Comment by maxemann96** [comment]
@stuartacott In this fork you can !votestart, simply download and compile it like told in the README. Do you encountered any problems with it?

**Comment by maxemann96** [comment]
Closed due to Patch 1.30.2
