### ISSUE TITLE
cant get !votestart to work

### ISSUE THREAD

**Issue by stuartacott** [maxemann96/ghostpp#3]
hi cant get votestart and !commands to works well the one to turn on none admin commands dont know if it needs to be in my config file or not but everything else seems to work sweet
bot_war3path = C:\Program Files (x86)\Warcraft III\
bot_tft = 0
bot_hostport = 6113
bot_mapcfgpath = C:\Program Files (x86)\Warcraft III\
bot_mappath = C:\Users\stuar\OneDrive\Documents\Warcraft III\Maps\Download\
bot_virtualhostname = |cFFFF0000lgn4
bnet_server = europe.battle.net
bnet_serveralias = euro
bnet_cdkeyroc = 
bnet_username = 
bnet_password = 
bnet_firstchannel = clan csb
bnet_rootadmin = stuart21swindon dukewayne t.i.m.e ugotsmurfed
bnet_custom_war3version = 30

**Comment by maxemann96** [comment]
What is the output of your log? Are you using the latest version? (The precompiled windows binary in this repository is still on Warcraft 1.29 and outdated, you must compile it yourself)

**Comment by stuartacott** [comment]
ahh ok how do i do that soz never done this before i have codeblocks

**Comment by stuartacott** [comment]
no soz thats bots confige file bot is al connect fine and autohost fine just cant get !votestart and !commads to work so non admin can use !start. looked through the ghost.cpp and stuff and all the code is in there for votestart.

**Comment by maxemann96** [comment]
Do you now compiled it under windows? What is the output of your ghost log?

**Comment by maxemann96** [comment]
Closing this because of no reaction ~3 weeks
