### ISSUE TITLE
Admin Game Not Working

### ISSUE THREAD

**Issue by aSilentSniper** [maxemann96/ghostpp#4]
[Mon Oct 01 21:53:50 2018] [GHOST] acting as Warcraft III: The Frozen Throne
[Mon Oct 01 21:53:50 2018] [CONFIG] loading file [language_german.cfg]
[Mon Oct 01 21:53:50 2018] [GHOST] missing bnet_username, skipping this battle.net connection
[Mon Oct 01 21:53:50 2018] [GHOST] warning - no battle.net connections found in config file
[Mon Oct 01 21:53:50 2018] [GHOST] warning - unable to load MPQ file [E:\server\Warcraft III\War3Patch.mpq] - error code 2
[Mon Oct 01 21:53:50 2018] [GHOST] adding ".cfg" to default map -> new default is [wormwar.cfg]
[Mon Oct 01 21:53:50 2018] [CONFIG] loading file [mapcfgs\wormwar.cfg]
[Mon Oct 01 21:53:50 2018] [UTIL] warning - unable to read file [E:\server\Warcraft III\Maps\(12)WormWar.w3x]
[Mon Oct 01 21:53:50 2018] [MAP] warning - unable to load MPQ file [E:\server\Warcraft III\Maps\(12)WormWar.w3x]
[Mon Oct 01 21:53:50 2018] [MAP] no map data available, using config file for map_size, map_info, map_crc, map_sha1
[Mon Oct 01 21:53:50 2018] [MAP] no map data available, using config file for map_options, map_width, map_height, map_slot<x>, map_numplayers, map_numteams
[Mon Oct 01 21:53:50 2018] [MAP] overriding calculated map_filter_type with config value map_filter_type = 0
[Mon Oct 01 21:53:50 2018] [GHOST] adding ".cfg" to default admin game map -> new default is [RagingStream.cfg]
[Mon Oct 01 21:53:50 2018] [GHOST] trying to load default admin game map
[Mon Oct 01 21:53:50 2018] [CONFIG] warning - unable to read file [mapcfgs\RagingStream.cfg]
[Mon Oct 01 21:53:50 2018] [MAP] warning - unable to load MPQ file [E:\server\Warcraft III\Maps\]
[Mon Oct 01 21:53:50 2018] [MAP] no map data available, using config file for map_size, map_info, map_crc, map_sha1
[Mon Oct 01 21:53:50 2018] [MAP] no map data available, using config file for map_options, map_width, map_height, map_slot<x>, map_numplayers, map_numteams
[Mon Oct 01 21:53:50 2018] [MAP] invalid map_path detected
[Mon Oct 01 21:53:51 2018] [MAP] invalid map_size detected
[Mon Oct 01 21:53:51 2018] [MAP] invalid map_info detected
[Mon Oct 01 21:53:51 2018] [MAP] invalid map_crc detected
[Mon Oct 01 21:53:51 2018] [MAP] invalid map_sha1 detected
[Mon Oct 01 21:53:51 2018] [MAP] invalid map_width detected
[Mon Oct 01 21:53:51 2018] [MAP] invalid map_height detected
[Mon Oct 01 21:53:51 2018] [MAP] invalid map_numplayers detected
[Mon Oct 01 21:53:51 2018] [MAP] invalid map_numteams detected
[Mon Oct 01 21:53:51 2018] [MAP] invalid map_slot<x> detected
[Mon Oct 01 21:53:51 2018] [GHOST] default admin game map isn't valid, using hardcoded admin game map instead
[Mon Oct 01 21:53:51 2018] [MAP] using hardcoded Emerald Gardens map data for Warcraft 3 version 1.24 & 1.24b
[Mon Oct 01 21:53:51 2018] [GHOST] started loading [ip-to-country.csv]
[Mon Oct 01 21:53:51 2018] [GHOST] iptocountry data: 10% loaded
[Mon Oct 01 21:53:52 2018] [GHOST] iptocountry data: 20% loaded
[Mon Oct 01 21:53:52 2018] [GHOST] iptocountry data: 30% loaded
[Mon Oct 01 21:53:53 2018] [GHOST] iptocountry data: 40% loaded
[Mon Oct 01 21:53:54 2018] [GHOST] iptocountry data: 50% loaded
[Mon Oct 01 21:53:54 2018] [GHOST] iptocountry data: 60% loaded
[Mon Oct 01 21:53:55 2018] [GHOST] iptocountry data: 70% loaded
[Mon Oct 01 21:53:56 2018] [GHOST] iptocountry data: 80% loaded
[Mon Oct 01 21:53:56 2018] [GHOST] iptocountry data: 90% loaded
[Mon Oct 01 21:53:57 2018] [GHOST] iptocountry data: 100% loaded
[Mon Oct 01 21:53:57 2018] [GHOST] finished loading [ip-to-country.csv]
[Mon Oct 01 21:53:57 2018] [GHOST] creating admin game
[Mon Oct 01 21:53:57 2018] [GAME: GHost++ Admin Game] loading IP blacklist file [ipblacklist.txt]
[Mon Oct 01 21:53:57 2018] [GAME: GHost++ Admin Game] loaded 635 lines from IP blacklist file
[Mon Oct 01 21:53:57 2018] [GAME: GHost++ Admin Game] attempting to bind to all available addresses
[Mon Oct 01 21:53:57 2018] [GAME: GHost++ Admin Game] listening on port 6113
[Mon Oct 01 21:53:57 2018] [GHOST] GHost++ Version 17.2 (with MySQL support)
[Mon Oct 01 21:54:13 2018] [GAME: GHost++ Admin Game] player [snipercommando|192.168.178.66] joined the game
[Mon Oct 01 21:54:13 2018] [GAME: GHost++ Admin Game] deleting player [snipercommando]: doesn't have the map and there is no local copy of the map to send

**Comment by aSilentSniper** [comment]
and i had no luck with compiling the latest version on windows

**Comment by maxemann96** [comment]
"[Mon Oct 01 21:53:50 2018] [GHOST] warning - unable to load MPQ file [E:\server\Warcraft III\War3Patch.mpq] - error code 2" is indicating that something is possibly broken with your MPQ-File. (Which wc3 version you are using? If using 1.29 you need "war3x.mpq" instead of "War3Patch.mpq", If using 1.30 u need the data folder which is the casc-container).

Also the server cannot read the map files (are they existing/readable for the server-software, permission problem?) Also you have many config and map file errors, no crc and sha of map are calculated, pls check your config files.

Do you have a output from your windows compiler?

Also pls don't expect any answer till next monday, since im very busy this week

**Comment by maxemann96** [comment]
Closing this because of no reaction ~2 weeks
