### ISSUE TITLE
Connect to the server normally but can't see the bot room.

### ISSUE THREAD

**Issue by Fatorin** [maxemann96/ghostpp#7]
Hello , I want run ghostpp on linux but has some problem.
I complete the configuration and successfully connect to the server, but I can't see bot room in game list.
I saw log and I sure bot created room success.
I think my linux system setting has problem so I try to adjust firewall setting, but still can't see game room.
I found most forum but haven't correct solution, hope you can help, Thanks.

I use Ubuntu 16.04 and Warcraft III version is 1.28F.

**Comment by maxemann96** [comment]
Closing as duplicate of https://github.com/uakfdotb/ghostpp/issues/33
