### ISSUE TITLE
Sometimes triggering GProxy reconnect will cause big lagging in all games.

### ISSUE THREAD

**Issue by Fatorin** [maxemann96/ghostpp#8]
Hello, I would like to ask, is there any way to avoid GProxy causing large lag problems?

I used Ghostpp and turn on gproxy on a pvpgn server.

Sometimes, when player triggering reconnect. All game players will cause big lag problem.

I notice the CPU usage has 100%. But I don't know how to improve this problem.

Can you tell me how to improve this status?

Ghost++ settings are, bot_latency : 31, sync_limit: 150
Client has used tool name is MyMGN GProxy DLL. War3 version is 1.28.5.

In the DLL introduction page, the "GProxy extension protocol" is mentioned.
I also want try import this extension protocol in Ghostpp, But not found more information on there forum.(code or any discuss)

Thanks for your read.

**Comment by maxemann96** [comment]
Hi Fatorin, thanks for using my fork of ghostpp. Unfortunately I did'nt use GProxy before and also the last time I looked into the code is a long time ago. So I cannot help you, sorry.

**Comment by Fatorin** [comment]
OK, thanks you reply me!
